local Library = 
local WS = game:GetService("Workspace")
local RS = game:GetService("ReplicatedStorage")
local PLRS = game:GetService("Pkayers")

local Player = PLRS.LocalPlayer
local Character = Player.Character


local Settings = {
  Auto_Click = false,
  Auto_Drain = false,
  Max_Stage = 0,
  Auto_Rebirth = false,
  Auto_Collect_Fish = false, -- fih
  Auto_Collect = false,

  Auto_Sell = false
}
